"""players table

Revision ID: 48c363c37898
Revises: 
Create Date: 2020-01-09 13:39:04.875708

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48c363c37898'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('position', sa.String(length=64), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('nationality', sa.String(length=64), nullable=True),
    sa.Column('href', sa.String(length=200), nullable=True),
    sa.Column('img_href', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_player_href'), 'player', ['href'], unique=True)
    op.create_index(op.f('ix_player_img_href'), 'player', ['img_href'], unique=True)
    op.create_index(op.f('ix_player_name'), 'player', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_player_name'), table_name='player')
    op.drop_index(op.f('ix_player_img_href'), table_name='player')
    op.drop_index(op.f('ix_player_href'), table_name='player')
    op.drop_table('player')
    # ### end Alembic commands ###
