"""empty message

Revision ID: 7f1bf6fa5caa
Revises: 6050971323cb
Create Date: 2020-01-14 07:25:40.078781

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f1bf6fa5caa'
down_revision = '6050971323cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_league_href', table_name='league')
    op.create_index(op.f('ix_league_href'), 'league', ['href'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_league_href'), table_name='league')
    op.create_index('ix_league_href', 'league', ['href'], unique=1)
    # ### end Alembic commands ###
