"""empty message

Revision ID: b940430245a3
Revises: 48c363c37898
Create Date: 2020-01-09 14:37:23.728902

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b940430245a3'
down_revision = '48c363c37898'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('league',
    sa.Column('id', sa.String(length=200), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('href', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_league_href'), 'league', ['href'], unique=True)
    op.create_index(op.f('ix_league_name'), 'league', ['name'], unique=False)
    op.create_table('club',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('country', sa.String(length=64), nullable=True),
    sa.Column('leagueId', sa.String(length=64), nullable=True),
    sa.Column('country_img_href', sa.String(length=200), nullable=True),
    sa.Column('club_img_href', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['leagueId'], ['league.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_club_club_img_href'), 'club', ['club_img_href'], unique=True)
    op.create_index(op.f('ix_club_country_img_href'), 'club', ['country_img_href'], unique=True)
    op.create_index(op.f('ix_club_name'), 'club', ['name'], unique=False)
    op.create_table('transfer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('playerId', sa.Integer(), nullable=True),
    sa.Column('fromId', sa.Integer(), nullable=True),
    sa.Column('toId', sa.Integer(), nullable=True),
    sa.Column('href', sa.String(length=200), nullable=True),
    sa.Column('value', sa.String(length=64), nullable=True),
    sa.Column('timestamp', sa.String(length=64), nullable=True),
    sa.Column('season', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['fromId'], ['club.id'], ),
    sa.ForeignKeyConstraint(['playerId'], ['player.id'], ),
    sa.ForeignKeyConstraint(['toId'], ['club.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('href')
    )
    op.drop_index('ix_player_name', table_name='player')
    op.create_index(op.f('ix_player_name'), 'player', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_player_name'), table_name='player')
    op.create_index('ix_player_name', 'player', ['name'], unique=1)
    op.drop_table('transfer')
    op.drop_index(op.f('ix_club_name'), table_name='club')
    op.drop_index(op.f('ix_club_country_img_href'), table_name='club')
    op.drop_index(op.f('ix_club_club_img_href'), table_name='club')
    op.drop_table('club')
    op.drop_index(op.f('ix_league_name'), table_name='league')
    op.drop_index(op.f('ix_league_href'), table_name='league')
    op.drop_table('league')
    # ### end Alembic commands ###
